function gui = callGUI()
    % Create the GUI
    namesOfGroups = {'Hand approaching', ...
                    'Hand reaching out', ...
                    'Grip type' ...
                    'Pointing [Robot workspace]', ...
                    'Pointing [Shared workspace]', ...
                    'Pointing [Human workspace]', ...
                    'Position of objects [Robot workspace]', ...
                    'Position of objects [Shared workspace]', ...
                    'Position of objects [Human workspace]', ...
                    'Stage of construction', ...
                    };
    numGroups = numel(namesOfGroups);
    namesOfFlagsPerGroup = {'Part 1', 'Part 2', 'Bracket 1', 'Bracket 2', 'Other'... % Hand approaching
                            'Toggle', ... % Hand reaching out
                            'A', 'B', 'C' ... % Grip type
                            'Part 1', 'Part 2', 'Bracket 1', 'Bracket 2', 'Other'... % Pointing [Robot workspace]
                            'Part 1', 'Part 2', 'Bracket 1', 'Bracket 2', 'Other'... % Pointing [Shared workspace]
                            'Part 1', 'Part 2', 'Bracket 1', 'Bracket 2', 'Other'... % Pointing [Human workspace]
                            'Part 1', 'Part 2', 'Bracket 1', 'Bracket 2', ... % Position of objects [Robot workspace]
                            'Part 1', 'Part 2', 'Bracket 1', 'Bracket 2', ... % Position of objects [Shared workspace]
                            'Part 1', 'Part 2', 'Bracket 1', 'Bracket 2', ... % Position of objects [Human workspace]
                            'Part 1', 'Part 2', 'Bracket 1', 'Bracket 2', ... % Stage of construction
                            };
    flagsPerGroup = [5 1 3 5 5 5 4 4 4 4];
    gui = BinaryFlagsGUI(numGroups, flagsPerGroup, namesOfGroups, namesOfFlagsPerGroup);
end
