function gui = callGUI()
    % Create the GUI
    namesOfGroups = {'Group A', 'Group B', 'Group C', 'Group D', 'Random'};
    numGroups = numel(namesOfGroups);
    namesOfFlagsPerGroup = {'a', 'b', 'c', ... 
                            'd', 'e', ...
                            't', 'y', 'h', 'j', ...
                            'i', 'o', 'a', ...
                            'y'};
    flagsPerGroup = [3 2 4 3 1];
    gui = BinaryFlagsGUI(numGroups, flagsPerGroup, namesOfGroups, namesOfFlagsPerGroup);
end
